### ISSUE TITLE
How to logout user ?

### ISSUE THREAD

**Issue by fahimbabarpatel** [scotch-io/node-token-authentication#2]
Hello,

I followed code. How to logout user using api and token ? I am building api for iPhone.

Thanks!

**Comment by ghost** [comment]
fagimbarbarpatel : could you please explain me how it working in case of logging and auth.

**Comment by fahimbabarpatel** [comment]
For logout , our mobile team is deleting token from devices so in next time request will get fail and redirected to login screen

**Comment by fahimbabarpatel** [comment]
@vaibhavjain882  https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens link have all information . 

Find and read below code in link. You will understood flow.

```
// route to authenticate a user (POST http://localhost:8080/api/authenticate)
apiRoutes.post('/authenticate', function(req, res) {


// route middleware to verify a token
apiRoutes.use(function(req, res, next) {

```
