### ISSUE TITLE
package.json - jsonwebtoken contains critical vulnerability

### ISSUE THREAD

**Issue by zinniacodes** [scotch-io/node-token-authentication#6]
This version of jsonwebtoken contains a critical authentication bypass vulnerability in asymmetric key signing prior to version 4.2.2.

I appreciate that this repo is probably unmaintained, however there is a risk to users learning about JWT auth who would modify the code to use RSA (or other asymmetric algorithm) instead of HMAC with the JWT library. This vulnerability could then end up in the wild.

**Comment by zinniacodes** [comment]
https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by chris-sev** [comment]
If you could throw together a pull request, I'd be happy to merge it in.

**Comment by eliottparis** [comment]
does #7 fixed this ?

**Comment by zinniacodes** [comment]
Yes, thanks
